### ISSUE TITLE
Python 3.8-3.10: cli command without options throws error

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/iBridges#328]
When calling `ibridges` without command line options (so without e.g. `--help`), the following error is thrown:

```
Traceback (most recent call last):
  File "/tmp/ibridges3.10/bin/ibridges", line 8, in <module>
    sys.exit(main())
  File "/tmp/ibridges3.10/lib/python3.10/site-packages/ibridges/cli/__main__.py", line 30, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

Reproduced on python 3.8 and 3.10. Everything works on 3.11.

**To Reproduce**

1. `uv python install 3.10`
2. `uv venv -p 3.10 /tmp/ibridges3.10`
3. `source /tmp/ibridges3.10/bin/activate`
4. `uv pip install ibridges`
5. `/tmp/ibridges3.10/bin/ibridges `

**Provide some information:**
 - OS: reproduced on OS X and Ubuntu
 - Software version: ibridges 1.5.0
 - python version: 3.8 - 3.10

**Comment by dometto** [comment]
Already adressed in https://github.com/iBridges-for-iRODS/iBridges/issues/322
